### ISSUE TITLE
Licencing for commercial project

### ISSUE THREAD

**Issue by blambeau** [feonit/olap-cube-js#5]
Hi there,

Your licence does not make it very clear whether the package can be used freely and/or embedded in a (commercial) project.

Could you clarify that please?
Thanks.

**Comment by feonit** [comment]
Hello, I find it a little difficult to choose a particular one, there are too many of them. ISC is automatically listed on the npm page, is this not enough?

**Comment by feonit** [comment]
MIT welcome
https://github.com/feonit/olap-cube-js/commit/232aaa74d6133fa7c2374ebd5cbd4384503a824b

**Comment by blambeau** [comment]
Thanks!
